"""`AGENTS.md` generation and update."""

from __future__ import annotations

from pathlib import Path

AGENTS_MD_TEMPLATE = """# AGENTS.md — AI Agent Instructions for {project_name}

> **Required first read:** `docs/AIprojectcontext/ai-index.md`
> **Primary context source:** `docs/AIprojectcontext/`
> **Generated by:** `aictx`

## Rules for all agents

1. Read `docs/AIprojectcontext/ai-index.md` first.
2. Do **not** read large human-facing public docs for general project context.
3. Public docs may be read only when the task is documentation-related or `aictx verify --strict` reports a public-docs impact.
4. Run `aictx verify --strict` before any public commit.
5. If context is stale, run `aictx run --project . --mode setup-context --scope full --write apply` to regenerate the full context scaffold.
   - Note: `--scope changed` refresh is not yet implemented.
6. If public docs are impacted, run `aictx public-docs update --project . --scope changed --write patch`.
   - Note: `public-docs update` is currently a stub and not yet implemented.
7. Do not fabricate facts. Mark missing information `unknown` or `needs-source`.
8. Preserve source references for all important claims.

## Accuracy rules

- Source-trace all critical claims.
- No unsupported assumptions.
- Mark uncertainty explicitly.
- Fail closed: report `unknown` rather than guess.
"""


def generate_agents_md(project_name: str) -> str:
    """Return the generated AGENTS.md content."""
    return AGENTS_MD_TEMPLATE.format(project_name=project_name)


def write_agents_md(repo_root: Path, project_name: str) -> Path:
    """Write AGENTS.md to *repo_root*."""
    path = repo_root / "AGENTS.md"
    path.write_text(generate_agents_md(project_name), encoding="utf-8")
    return path
